# Generated by Django 4.1.4 on 2023-01-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='last',
            new_name='second_name',
        ),
    ]
